# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dysense_designer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1255, 810)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.main_status_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.main_status_label.setFont(font)
        self.main_status_label.setObjectName(_fromUtf8("main_status_label"))
        self.horizontalLayout_7.addWidget(self.main_status_label)
        self.main_status_line_edit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_status_line_edit.sizePolicy().hasHeightForWidth())
        self.main_status_line_edit.setSizePolicy(sizePolicy)
        self.main_status_line_edit.setObjectName(_fromUtf8("main_status_line_edit"))
        self.horizontalLayout_7.addWidget(self.main_status_line_edit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.menu_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_button.sizePolicy().hasHeightForWidth())
        self.menu_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.menu_button.setFont(font)
        self.menu_button.setObjectName(_fromUtf8("menu_button"))
        self.horizontalLayout.addWidget(self.menu_button)
        self.visualize_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualize_button.sizePolicy().hasHeightForWidth())
        self.visualize_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.visualize_button.setFont(font)
        self.visualize_button.setObjectName(_fromUtf8("visualize_button"))
        self.horizontalLayout.addWidget(self.visualize_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sensor_group_box = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_group_box.sizePolicy().hasHeightForWidth())
        self.sensor_group_box.setSizePolicy(sizePolicy)
        self.sensor_group_box.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sensor_group_box.setFont(font)
        self.sensor_group_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sensor_group_box.setObjectName(_fromUtf8("sensor_group_box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.sensor_group_box)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.test_sensor_radio_button = QtGui.QRadioButton(self.sensor_group_box)
        self.test_sensor_radio_button.setObjectName(_fromUtf8("test_sensor_radio_button"))
        self.verticalLayout_2.addWidget(self.test_sensor_radio_button)
        self.horizontalLayout_2.addWidget(self.sensor_group_box)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stacked_widget = QtGui.QStackedWidget(self.centralwidget)
        self.stacked_widget.setObjectName(_fromUtf8("stacked_widget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.stop_sensors_button = QtGui.QPushButton(self.page)
        self.stop_sensors_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stop_sensors_button.setFont(font)
        self.stop_sensors_button.setObjectName(_fromUtf8("stop_sensors_button"))
        self.gridLayout_3.addWidget(self.stop_sensors_button, 2, 1, 1, 1)
        self.setup_sensors_button = QtGui.QPushButton(self.page)
        self.setup_sensors_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.setup_sensors_button.setFont(font)
        self.setup_sensors_button.setObjectName(_fromUtf8("setup_sensors_button"))
        self.gridLayout_3.addWidget(self.setup_sensors_button, 1, 0, 1, 1)
        self.pause_sensor_button = QtGui.QPushButton(self.page)
        self.pause_sensor_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pause_sensor_button.setFont(font)
        self.pause_sensor_button.setObjectName(_fromUtf8("pause_sensor_button"))
        self.gridLayout_3.addWidget(self.pause_sensor_button, 2, 0, 1, 1)
        self.start_sensor_button = QtGui.QPushButton(self.page)
        self.start_sensor_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start_sensor_button.setFont(font)
        self.start_sensor_button.setObjectName(_fromUtf8("start_sensor_button"))
        self.gridLayout_3.addWidget(self.start_sensor_button, 1, 1, 1, 1)
        self.message_center_text_edit = QtGui.QTextEdit(self.page)
        self.message_center_text_edit.setObjectName(_fromUtf8("message_center_text_edit"))
        self.gridLayout_3.addWidget(self.message_center_text_edit, 3, 0, 1, 1)
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stacked_widget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stacked_widget, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1255, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.main_status_label.setText(_translate("MainWindow", "Status:", None))
        self.menu_button.setText(_translate("MainWindow", "MENU", None))
        self.visualize_button.setText(_translate("MainWindow", "Visualize", None))
        self.sensor_group_box.setTitle(_translate("MainWindow", "Sensors", None))
        self.test_sensor_radio_button.setText(_translate("MainWindow", "Test Sensor", None))
        self.stop_sensors_button.setText(_translate("MainWindow", "Stop Sensors", None))
        self.setup_sensors_button.setText(_translate("MainWindow", "Setup Sensors", None))
        self.pause_sensor_button.setText(_translate("MainWindow", "Pause Sensors", None))
        self.start_sensor_button.setText(_translate("MainWindow", "Start Sensors", None))

