# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensor_view_widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(866, 706)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sensor_status_group_box = QtGui.QGroupBox(Form)
        self.sensor_status_group_box.setTitle(_fromUtf8(""))
        self.sensor_status_group_box.setObjectName(_fromUtf8("sensor_status_group_box"))
        self.gridLayout_3 = QtGui.QGridLayout(self.sensor_status_group_box)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sensor_health_label = QtGui.QLabel(self.sensor_status_group_box)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sensor_health_label.setFont(font)
        self.sensor_health_label.setObjectName(_fromUtf8("sensor_health_label"))
        self.gridLayout_3.addWidget(self.sensor_health_label, 0, 0, 1, 1)
        self.sensor_health_icon_label = QtGui.QLabel(self.sensor_status_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_health_icon_label.sizePolicy().hasHeightForWidth())
        self.sensor_health_icon_label.setSizePolicy(sizePolicy)
        self.sensor_health_icon_label.setMinimumSize(QtCore.QSize(65, 63))
        self.sensor_health_icon_label.setText(_fromUtf8(""))
        self.sensor_health_icon_label.setObjectName(_fromUtf8("sensor_health_icon_label"))
        self.gridLayout_3.addWidget(self.sensor_health_icon_label, 0, 1, 1, 1)
        self.sensor_state_label = QtGui.QLabel(self.sensor_status_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_state_label.sizePolicy().hasHeightForWidth())
        self.sensor_state_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sensor_state_label.setFont(font)
        self.sensor_state_label.setObjectName(_fromUtf8("sensor_state_label"))
        self.gridLayout_3.addWidget(self.sensor_state_label, 1, 0, 1, 1)
        self.sensor_state_line_edit = QtGui.QLineEdit(self.sensor_status_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_state_line_edit.sizePolicy().hasHeightForWidth())
        self.sensor_state_line_edit.setSizePolicy(sizePolicy)
        self.sensor_state_line_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sensor_state_line_edit.setObjectName(_fromUtf8("sensor_state_line_edit"))
        self.gridLayout_3.addWidget(self.sensor_state_line_edit, 1, 1, 1, 1)
        self.paused_label = QtGui.QLabel(self.sensor_status_group_box)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.paused_label.setFont(font)
        self.paused_label.setObjectName(_fromUtf8("paused_label"))
        self.gridLayout_3.addWidget(self.paused_label, 2, 0, 1, 1)
        self.paused_line_edit = QtGui.QLineEdit(self.sensor_status_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paused_line_edit.sizePolicy().hasHeightForWidth())
        self.paused_line_edit.setSizePolicy(sizePolicy)
        self.paused_line_edit.setObjectName(_fromUtf8("paused_line_edit"))
        self.gridLayout_3.addWidget(self.paused_line_edit, 2, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.sensor_status_group_box)
        self.sensor_info_group_box = QtGui.QGroupBox(Form)
        self.sensor_info_group_box.setTitle(_fromUtf8(""))
        self.sensor_info_group_box.setObjectName(_fromUtf8("sensor_info_group_box"))
        self.gridLayout_2 = QtGui.QGridLayout(self.sensor_info_group_box)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sensor_name_label = QtGui.QLabel(self.sensor_info_group_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_name_label.setFont(font)
        self.sensor_name_label.setObjectName(_fromUtf8("sensor_name_label"))
        self.gridLayout_2.addWidget(self.sensor_name_label, 1, 0, 1, 1)
        self.sensor_type_label = QtGui.QLabel(self.sensor_info_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_type_label.sizePolicy().hasHeightForWidth())
        self.sensor_type_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_type_label.setFont(font)
        self.sensor_type_label.setObjectName(_fromUtf8("sensor_type_label"))
        self.gridLayout_2.addWidget(self.sensor_type_label, 2, 0, 1, 1)
        self.sensor_id_label = QtGui.QLabel(self.sensor_info_group_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_id_label.setFont(font)
        self.sensor_id_label.setToolTip(_fromUtf8(""))
        self.sensor_id_label.setObjectName(_fromUtf8("sensor_id_label"))
        self.gridLayout_2.addWidget(self.sensor_id_label, 4, 0, 1, 1)
        self.sensor_id_line_edit = QtGui.QLineEdit(self.sensor_info_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_id_line_edit.sizePolicy().hasHeightForWidth())
        self.sensor_id_line_edit.setSizePolicy(sizePolicy)
        self.sensor_id_line_edit.setObjectName(_fromUtf8("sensor_id_line_edit"))
        self.gridLayout_2.addWidget(self.sensor_id_line_edit, 4, 1, 1, 1)
        self.capture_rate_label = QtGui.QLabel(self.sensor_info_group_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.capture_rate_label.setFont(font)
        self.capture_rate_label.setObjectName(_fromUtf8("capture_rate_label"))
        self.gridLayout_2.addWidget(self.capture_rate_label, 5, 0, 1, 1)
        self.capture_rate_line_edit = QtGui.QLineEdit(self.sensor_info_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capture_rate_line_edit.sizePolicy().hasHeightForWidth())
        self.capture_rate_line_edit.setSizePolicy(sizePolicy)
        self.capture_rate_line_edit.setObjectName(_fromUtf8("capture_rate_line_edit"))
        self.gridLayout_2.addWidget(self.capture_rate_line_edit, 5, 1, 1, 1)
        self.sensor_name_line_edit = QtGui.QLineEdit(self.sensor_info_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_name_line_edit.sizePolicy().hasHeightForWidth())
        self.sensor_name_line_edit.setSizePolicy(sizePolicy)
        self.sensor_name_line_edit.setObjectName(_fromUtf8("sensor_name_line_edit"))
        self.gridLayout_2.addWidget(self.sensor_name_line_edit, 1, 1, 1, 1)
        self.sensor_type_line_edit = QtGui.QLineEdit(self.sensor_info_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_type_line_edit.sizePolicy().hasHeightForWidth())
        self.sensor_type_line_edit.setSizePolicy(sizePolicy)
        self.sensor_type_line_edit.setObjectName(_fromUtf8("sensor_type_line_edit"))
        self.gridLayout_2.addWidget(self.sensor_type_line_edit, 2, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.sensor_info_group_box)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.message_center_label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.message_center_label.setFont(font)
        self.message_center_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.message_center_label.setObjectName(_fromUtf8("message_center_label"))
        self.verticalLayout_3.addWidget(self.message_center_label)
        self.sensor_message_center_text_edit = QtGui.QTextEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_message_center_text_edit.sizePolicy().hasHeightForWidth())
        self.sensor_message_center_text_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sensor_message_center_text_edit.setFont(font)
        self.sensor_message_center_text_edit.setObjectName(_fromUtf8("sensor_message_center_text_edit"))
        self.verticalLayout_3.addWidget(self.sensor_message_center_text_edit)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clear_sensor_message_center_button = QtGui.QPushButton(Form)
        self.clear_sensor_message_center_button.setObjectName(_fromUtf8("clear_sensor_message_center_button"))
        self.horizontalLayout.addWidget(self.clear_sensor_message_center_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.commands_group_box = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commands_group_box.sizePolicy().hasHeightForWidth())
        self.commands_group_box.setSizePolicy(sizePolicy)
        self.commands_group_box.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.commands_group_box.setFont(font)
        self.commands_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.commands_group_box.setObjectName(_fromUtf8("commands_group_box"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.commands_group_box)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.connect_sensor_button = QtGui.QPushButton(self.commands_group_box)
        self.connect_sensor_button.setMinimumSize(QtCore.QSize(0, 30))
        self.connect_sensor_button.setObjectName(_fromUtf8("connect_sensor_button"))
        self.horizontalLayout_6.addWidget(self.connect_sensor_button)
        self.pause_sensor_button = QtGui.QPushButton(self.commands_group_box)
        self.pause_sensor_button.setMinimumSize(QtCore.QSize(0, 30))
        self.pause_sensor_button.setObjectName(_fromUtf8("pause_sensor_button"))
        self.horizontalLayout_6.addWidget(self.pause_sensor_button)
        self.remove_sensor_button = QtGui.QPushButton(self.commands_group_box)
        self.remove_sensor_button.setObjectName(_fromUtf8("remove_sensor_button"))
        self.horizontalLayout_6.addWidget(self.remove_sensor_button)
        self.verticalLayout.addWidget(self.commands_group_box)
        self.extra_commands_group_box = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extra_commands_group_box.sizePolicy().hasHeightForWidth())
        self.extra_commands_group_box.setSizePolicy(sizePolicy)
        self.extra_commands_group_box.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.extra_commands_group_box.setFont(font)
        self.extra_commands_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.extra_commands_group_box.setObjectName(_fromUtf8("extra_commands_group_box"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.extra_commands_group_box)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.extra_command1_button = QtGui.QPushButton(self.extra_commands_group_box)
        self.extra_command1_button.setMinimumSize(QtCore.QSize(0, 30))
        self.extra_command1_button.setObjectName(_fromUtf8("extra_command1_button"))
        self.horizontalLayout_8.addWidget(self.extra_command1_button)
        self.extra_command2_button = QtGui.QPushButton(self.extra_commands_group_box)
        self.extra_command2_button.setMinimumSize(QtCore.QSize(0, 30))
        self.extra_command2_button.setObjectName(_fromUtf8("extra_command2_button"))
        self.horizontalLayout_8.addWidget(self.extra_command2_button)
        self.verticalLayout.addWidget(self.extra_commands_group_box)
        self.extra_commands_group_box.raise_()
        self.commands_group_box.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.sensor_health_label.setText(_translate("Form", "Sensor Health:", None))
        self.sensor_state_label.setText(_translate("Form", "Sensor State:", None))
        self.paused_label.setText(_translate("Form", "Paused:", None))
        self.sensor_name_label.setText(_translate("Form", "Sensor Name", None))
        self.sensor_type_label.setText(_translate("Form", "Sensor Type", None))
        self.sensor_id_label.setText(_translate("Form", "Sensor ID", None))
        self.capture_rate_label.setText(_translate("Form", "Capture Rate", None))
        self.message_center_label.setText(_translate("Form", "Message Center", None))
        self.clear_sensor_message_center_button.setText(_translate("Form", "Clear Message Center", None))
        self.commands_group_box.setTitle(_translate("Form", "Commands", None))
        self.connect_sensor_button.setText(_translate("Form", "Connect", None))
        self.pause_sensor_button.setText(_translate("Form", "Pause", None))
        self.remove_sensor_button.setText(_translate("Form", "Remove", None))
        self.extra_commands_group_box.setTitle(_translate("Form", "Extra Commands", None))
        self.extra_command1_button.setText(_translate("Form", "EC 1", None))
        self.extra_command2_button.setText(_translate("Form", "EC 2", None))

